version: '2.0'

services:

  elasticsearch:
    restart: always
    mem_limit: 2048m
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      discovery.type: single-node